### ISSUE TITLE
No response for location from address

### ISSUE THREAD

**Issue by dev4jam** [malcommac/SwiftLocation#187] opened 2018-01-16 20:24 UTC
If I make a call:

```swift
Locator.location(fromAddress: address, onSuccess: { (places) -> (Void) in
```

then I don't receive a response. Probably because in GeocoderRequest class there is no handler call in block on line 215:

```swift
geocoder.geocodeAddressString(address, in: region, completionHandler: { (placemarks, error) in
	self.isFinished = true
})
```

**Comment by TizianoCoroneo** [comment] 2018-03-15 12:54
+1

**Comment by malcommac** [comment] 2018-03-16 18:58
The problem is with memory managment; if not assigned to a strong variable request is not keeped alive from SwiftLocation and the entire object will be deallocated.
Since 3.2.0 as for location and heading requests, geocoder requests are keeped alive by the library itself and removed automatically once request is fulfilled or rejected.
Thanks for reporting.

**Closed as completed** 2018-03-16 18:58 UTC
Labels: bug
