### ISSUE TITLE
Locator.events.listen closure is never called

### ISSUE THREAD

**Issue by nderkach** [malcommac/SwiftLocation#173] opened 2017-12-02 13:13 UTC
I'm using the code from the master branch, here is the sample:

```swift
Locator.requestAuthorizationIfNeeded(.whenInUse)
Locator.events.listen { newStatus in
    print("\(newStatus)")
}
```

Then if I try to change location authorisation in the settings, this closure is never called. Am I using it wrong?

**Comment by malcommac** [comment] 2017-12-07 10:12
Duplicate of this PR.
https://github.com/malcommac/SwiftLocation/pull/169

Thanks 👍

**Closed as completed by malcommac** 2017-12-07 10:12 UTC
Labels: duplicate
